# Generated by Django 6.0.5 on 2026-05-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campania', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('SE', 'Semanal'), ('QU', 'Quincenal'), ('ME', 'Mensual')], default='SE', max_length=2)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objetivo', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campanas_marketing',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('url_origen', models.URLField(blank=True, max_length=250, null=True)),
                ('paginas_visitadas', models.PositiveIntegerField(default=0)),
                ('tiempo_sesion_seg', models.PositiveIntegerField(default=0)),
                ('descargo_prueba', models.BooleanField(default=False)),
                ('score_calificacion', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('NU', 'Nuevo'), ('CO', 'Contactado'), ('CA', 'Calificado'), ('CV', 'Convertido'), ('DE', 'Descartado')], default='NU', max_length=2)),
                ('convertido_cliente', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'db_table': 'prospectos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('zona', models.CharField(max_length=20)),
                ('meta_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='MetricaCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enviadas', models.PositiveIntegerField(default=0)),
                ('total_abiertas', models.PositiveIntegerField(default=0)),
                ('total_respondidas', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('tasa_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tasa_respuesta', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('campana', models.ForeignKey(db_column='campana_id', on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='crm.campanamarketing')),
            ],
            options={
                'verbose_name': 'Métrica de Campaña',
                'verbose_name_plural': 'Métricas de Campaña',
                'db_table': 'metricas_campana',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('EM', 'Email'), ('LL', 'Llamada'), ('VW', 'Visita web'), ('DE', 'Demo'), ('DS', 'Descarga')], max_length=2)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('abierto', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('genera_alerta', models.BooleanField(default=False)),
                ('campana', models.ForeignKey(blank=True, db_column='campana_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to='crm.campanamarketing')),
                ('prospecto', models.ForeignKey(db_column='prospecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Interacción de Marketing',
                'verbose_name_plural': 'Interacciones de Marketing',
                'db_table': 'interacciones_marketing',
                'ordering': ['-fecha_interaccion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('tipo_cliente', models.CharField(choices=[('EM', 'Empresa'), ('IN', 'Institución'), ('ID', 'Individual')], default='EM', max_length=2)),
                ('fecha_conversion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('prospecto', models.OneToOneField(blank=True, db_column='prospecto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_conversion'],
            },
        ),
        migrations.AddField(
            model_name='prospecto',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='crm.vendedor'),
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_licencia', models.CharField(choices=[('BA', 'Básica'), ('PR', 'Profesional'), ('EM', 'Empresarial')], default='BA', max_length=2)),
                ('num_usuarios', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('EN', 'Enviada'), ('AC', 'Aceptada'), ('RE', 'Rechazada'), ('VE', 'Vencida')], default='EN', max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('prospecto', models.ForeignKey(db_column='prospecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='crm.prospecto')),
                ('vendedor', models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to='crm.vendedor')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'db_table': 'propuestas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='campanamarketing',
            name='vendedor_responsable',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias', to='crm.vendedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('TA', 'Tarjeta'), ('TR', 'Transferencia'), ('PP', 'PayPal')], default='TR', max_length=2)),
                ('estado_pago', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('RE', 'Rechazado')], default='PE', max_length=2)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='crm.cliente')),
                ('propuesta', models.OneToOneField(db_column='propuesta_id', on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='crm.propuesta')),
                ('vendedor', models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='crm.vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
