# Generated by Django 5.0.14 on 2026-05-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_campanamarketing_id_alter_cliente_id_and_more'),
        ('crm', '0002_alter_vendedor_options_vendedor_usuario'),
    ]

    operations = [
    ]
