# Generated by Django 6.0.5 on 2026-05-29 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_campanamarketing_id_alter_cliente_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanamarketing',
            name='vendedor_responsable',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
